version: '3.5'

services:
  meilisearch-ui:
    image: riccoxie/meilisearch-ui:latest
    container_name: meilisearch-ui
    restart: always
    ports:
      - "3001:24900"

  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=MASTER_KEY
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    command: ["meilisearch"]
